name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build
        run: |
          npm ci
          npm run test
          npm run build
          npm version ${{ github.ref_name }} --no-git-tag-version

      - name: Publish
        uses: JS-DevTools/npm-publish@v2
        with:
          access: 'public'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
