name: Publish

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build
        run: |
          npm ci
          npm run test
          npm run build

      - name: Publish
        run: |
          npm version ${{ github.ref_name }} --no-git-tag-version
          npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
