name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install / PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install / NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18'
          registry-url: 'https://registry.npmjs.org' # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm test
          pnpm build

      - name: Publish
        run: |
          pnpm version ${{ github.ref_name }} --no-git-tag-version
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
